
version: '3.6'

services:

    grafana:
        image: ${REPO_GRAFANA}
        container_name: grafana
        ports:
          - 3001:3000
    
    mysqldb:
        image: ${REPO_MARIADB}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        container_name: mysqldb
        ports:
          - 13306:3306


